# Generated by Django 4.1.5 on 2023-01-26 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('image_url', models.FileField(upload_to='')),
                ('duration_seconds', models.IntegerField()),
            ],
        ),
    ]
