# Generated by Django 4.1.5 on 2023-02-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_audio_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
