# Generated by Django 4.1.5 on 2023-02-09 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='lib',
            field=models.ManyToManyField(related_name='audiolib', to=settings.AUTH_USER_MODEL),
        ),
    ]
