# Generated by Django 4.1.5 on 2023-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_audio_lib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='yt_id',
            field=models.CharField(max_length=100),
        ),
    ]
